# Autopilot Pattern NFS server implementation

nfsserver:
    image: autopilotpattern/nfsserver
    privileged: true
    mem_limit: 256m
    restart: always
    labels:
      - triton.cns.services=nfsnfsserver
    expose:
      - 111
      - 1892
      - 2049
    env_file: _env

# Start with a single host which will bootstrap the cluster.
# In production we'll want to use an HA cluster.
consul:
    image: progrium/consul:latest
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    ports:
      - 8500
    dns:
       - 127.0.0.1
    labels:
      - triton.cns.services=consul
    command: -server -bootstrap -ui-dir /ui