nfsserver:
    extends:
      file: docker-compose.yml
      service: nfsserver
    build: .
    mem_limit: 128g
    environment:
      - CONSUL=consul
    links:
      - consul:consul
    ports:
      - "111:111"
      - "1892:1892"
      - "2049:2049"

consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
      - "8500:8500"    
